make dist_min:
  gcc punto.o dist_min.o -o dist_min.exe

make dist_max:
	gcc punto.o dist_max.o -o dist_max.exe

punto.o:
  gcc -c punto.c

dist_min.o:
  gcc -c dist_min.c

dist_max:
	gcc -c dist_max.c

make clean:
  rm -f punto.o dist_min.o dist_min.exe
