distMin: punto.o distMin.o
	gcc punto.o distMin.o -o distMin.exe

distMax: punto.o distMax.o
	gcc punto.o distMax.o -o distMax.exe

punto.o:
	gcc -c punto.c

distMin.o:
	gcc -c distMin.c

distMax.o:
	gcc -c distMax.c

clean:
	rm -f punto.o distMin.o distMin.exe distMax.o distMax.exe
